spring:
  datasource:
    url: jdbc:h2:mem:demo;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl_auto: create

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  file:
    name: ./log/local

base-url: http://localhost:8080/api/email/userVerification
